### PR TITLE
fix: Centering the time display

### LINKED ISSUE #31: Time display moves noticably

### PR DESCRIPTION
**Pull request by Sasszem**
Closes #31

### CODE REVIEW

**Comment by Btimes2** [comment]
Screenshot_20200624_013114
Alapvetően oké, de most látványosan balra hord szerintem. Van valami más ötleted?

**Comment by Sasszem** [comment]
Ok, I tracked down the root cause of this off-center problem. The thing is, my previous centering code was perfect, it centered it based on the dynamic size, and that caused it to move noticably when the numbers changed. Now, it is "centered" based on the width of the widest character, and this causes it to be off-centered if our number is shorter than this.

I am thinking about a good solution. 
- going back to the original would mean it's centered, but moving
- maybe we should left-align it to a position based on a fix width? 

Idk, it won't ever be perfect...
What do you think, @Btimes2?

**Review by Btimes2 — CHANGES_REQUESTED** [review]
It is still a bit on the left.
The best solution is to change the timer's font to Open Sans later (added on Btimes2 branch), where numbers already have the same width to avoid such issues.

**Comment by Sasszem** [comment]
So, use a monospace font...
Yea, that would be the best solution, and we are already looking for a "default" font.

**Comment by Btimes2** [comment]
I added a font on my branch, it just has to be merged.

**Comment by Sasszem** [comment]
> I added a font on my branch, it just has to be merged.

Just do not forget to add `closes #34` to it, so it will auto-close this as well.

**Comment by Sasszem** [comment]
With a new font, the solution will be different.

**Pull request closed without merging**
