### PR TITLE
Change game to use roman numerals

### LINKED ISSUE #30: Change numbers into roman numerals

### LINKED ISSUE #45: Split up options screen

### PR DESCRIPTION
**Pull request by Sasszem**
Closes #30

### CODE REVIEW

**Review by Btimes2 — DISMISSED** [review]
I love it :) But could you please make it optional?

**Comment by Sasszem** [comment]
Updated, please review again, @Btimes2!
Also closes #45

**Review by Btimes2 — COMMENTED** [review]
Perfect implementation. I only wonder why you did not include the Roman numerals above 15. Is 16 so hard to reach that no user will ever reasonably get it?

Btw I did not check the new Options Menu code thoroughly, but I tested it and it works just as expected.

**Comment by Btimes2** [comment]
I see you decided to always write the game's name with Roman numerals :)

**Comment by Sasszem** [comment]
> Perfect implementation. I only wonder why you did not include the Roman numerals above 15. Is 16 so hard to reach that no user will ever reasonably get it?

The game ends on 13, so yea, no one will get there without cheating...

**Comment by Sasszem** [comment]
> I see you decided to always write the game's name with Roman numerals :)

I forgot about that. Shall I make that also optional?

**Comment by Btimes2** [comment]
> > Perfect implementation. I only wonder why you did not include the Roman numerals above 15. Is 16 so hard to reach that no user will ever reasonably get it?
> 
> The game ends on 13, so yea, no one will get there without cheating...

In that case it is okay.



> > I see you decided to always write the game's name with Roman numerals :)
> 
> I forgot about that. Shall I make that also optional?

Yeah, what if the game title text would be only XIII if the Roman numbers option is turned on? For the sake of those poor people without humor.

**Comment by Btimes2** [comment]
I tested it, it works nicely. 
I did not push the merge button yet bc I don't really understand how it works, and I am also not sure about the direction of this merge (master INTO roman?)

**Pull request merged**
